import type { CronogramaMarketing } from '@/server/db/types'

// ─── Re-export DB type with alias used by existing code ───────
export type MarketingCronograma = CronogramaMarketing

// ─── Rich post format (generated by the new /gerar-cronograma) ─

export interface MarketingPostRico {
  dia: number                                          // day of month (1-31)
  data: string                                         // YYYY-MM-DD
  plataforma: 'Instagram' | 'WhatsApp' | 'TikTok'
  formato: 'Reels' | 'Carrossel' | 'Story' | 'Feed'
  tema: string
  ideia_visual: string                                 // what to film/photograph
  legenda: string
  hashtags: string[]
  horario_sugerido: string
  cta: string                                          // call-to-action
  data_comemorativa?: string                           // holiday name if special
}

// ─── Re-export from the canonical datas-comemorativas module ─
// Single source of truth for holiday types/helpers.

export type { DataComemorativaBr } from '@/lib/datas-comemorativas'
export { getDatasComemorativasBr } from '@/lib/datas-comemorativas'

// ─── Form / API ───────────────────────────────────────────────

export interface CronogramaInput {
  mes: number
  ano: number
  datas_especiais: import('@/lib/datas-comemorativas').DataComemorativaBr[]
  produtos: string[]          // product names to highlight
}

export interface MarketingCronogramaInput {
  tipo_negocio: string
  publico_alvo: string
  periodo_dias: number
  foco: string
}

// ─── Constants ────────────────────────────────────────────────

export const MESES_PT = [
  'Janeiro','Fevereiro','Março','Abril','Maio','Junho',
  'Julho','Agosto','Setembro','Outubro','Novembro','Dezembro',
]

export const FORMATO_COLORS: Record<string, string> = {
  Reels:     'bg-red-100 text-red-700 border-red-200',
  Carrossel: 'bg-blue-100 text-blue-700 border-blue-200',
  Story:     'bg-purple-100 text-purple-700 border-purple-200',
  Feed:      'bg-green-100 text-green-700 border-green-200',
}

export const PLATAFORMA_COLORS: Record<string, string> = {
  Instagram: 'bg-pink-100 text-pink-700',
  WhatsApp:  'bg-green-100 text-green-700',
  TikTok:    'bg-gray-100 text-gray-700',
}

export const TIPOS_NEGOCIO = [
  'Confeitaria artesanal','Doceria fina','Bolos personalizados',
  'Doces para festas','Brigadeiros gourmet','Bolos fitness/veganos',
] as const

export const PUBLICOS_ALVO = [
  'Mães com filhos pequenos','Festas e eventos','Casamentos e datas especiais',
  'Público fitness/saudável','Corporativo','Público geral',
] as const

export const FOCOS_PERIODO = [
  'Vender mais','Ganhar seguidores','Mostrar bastidores',
  'Lançar produto novo','Data comemorativa','Depoimentos de clientes',
] as const
